### PR TITLE
Create field33-head-of-ux-and-data-visualization.md

### PR DESCRIPTION
**Pull request by sebastian-field33**

### CODE REVIEW

**Comment by sebastian-field33** [comment]
thank you

**Comment by z3to** [comment]
Why did you close it again? Shouldn’t the job be merged into the website?

**Comment by sebastian-field33** [comment]
Hi Jonas, thanks for asking. Not a Git expert. Yes should have been merged but I did not have the privileges. Can you help?

Thanks,
Sebastian

**Comment by z3to** [comment]
Done :)

**Pull request merged**
